# Generated by Django 5.2.8 on 2025-11-19 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("summary", models.TextField()),
                ("content", models.TextField()),
                ("read_time", models.IntegerField(help_text="Время чтения в минутах")),
                ("date", models.DateField()),
                ("category_tag", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("LANG", "Языки программирования"),
                            ("FRAMEWORK", "ML/AI Фреймворки"),
                            ("TOOL", "Инструменты & Библиотеки"),
                            ("DB", "Базы данных"),
                            ("DEVOPS", "DevOps/Инструменты"),
                            ("SPEC", "Специализации"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#667eea",
                        help_text="HEX цвет или название класса",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=100)),
                ("text", models.TextField()),
                ("emoji", models.CharField(default="👨\u200d💻", max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-адрес проекта (например: jarvis)", unique=True
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        help_text="Для карточки на главной", max_length=300
                    ),
                ),
                (
                    "full_description",
                    models.TextField(help_text="Полное описание для страницы проекта"),
                ),
                ("github_link", models.URLField(blank=True)),
                (
                    "metric_speed",
                    models.CharField(
                        blank=True, help_text="Например: <200ms", max_length=50
                    ),
                ),
                (
                    "metric_accuracy",
                    models.CharField(
                        blank=True, help_text="Например: 95%", max_length=50
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "technologies",
                    models.ManyToManyField(related_name="projects", to="main.skill"),
                ),
            ],
        ),
    ]
