# Generated by Django 6.0.4 on 2026-04-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="code_snippet",
            field=models.TextField(
                blank=True, help_text="Пример ключевого кода для демонстрации"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="features_list",
            field=models.TextField(
                blank=True, help_text="Список возможностей (каждая с новой строки)"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="how_it_works",
            field=models.TextField(
                blank=True, help_text="Подробное объяснение принципа работы проекта"
            ),
        ),
    ]
